### ISSUE TITLE
Asset location 

### ISSUE THREAD

**Issue by nova-alex** [rounders/ember-world-flags#45]
I apologize this was already asked in #27, but there was no elaboration and I'm experiencing the same issue.

Steps to reproduce:

1. `ember install ember-world-flags`
2. `ember build --dist`
3. `ember-world-flags/` folder in root of `/dist`

Expected behaviour:

`ember-world-flags/` folder in `/public/assets`

Maybe I'm doing something wrong but I'd be very grateful for a pointer.

**Comment by rounders** [comment]
@nova-alex thanks for the report and steps to reproduce. I'll see if I can get that fixed up in next day or two.

**Comment by rounders** [comment]
@nova-alex in step 2, `ember build --dist`, --dist doesn't seem to be a valid option to the build command. Can you clarify what the actual option you are running is?

**Comment by artsyca** [comment]
Sorry, I meant `ember build --prod` (the above is my work account)

Essentially the app is running in a subfolder like `/main/app` so I dump the entire `dist` folder into there and the assets are in `/main/app/assets/` but `/ember-world-flags/images/` remains at the root, it doesn't get merged with the assets folder. It's supposed to be in `/assets/ember-world-flags` according to the documentation: https://cli.emberjs.com/release/writing-addons/#public

<img width="411" alt="image" src="https://user-images.githubusercontent.com/364015/217682030-3223b443-8539-486f-a426-af3fc195cd4d.png">

**Comment by artsyca** [comment]
I think there's a nuance I'm not getting here. The assets are actually getting placed in the correct location according to the docs. They're in the root of `dist/` but the vendor css file is looking for them in the wrong place...

**Comment by rounders** [comment]
@artsyca thanks for the additional info, it's very helpful! I think you nailed it when mentioning that the css is looking for them in the wrong place. I'm just testing a branch now that I'm hoping might fix that.

**Comment by rounders** [comment]
@artsyca if you get a chance, could you try out this branch: https://github.com/rounders/ember-world-flags/tree/testing-paths. You can do so by changing the ember-world-flags entry in your package.json file to be: 
```
"ember-world-flags": "https://github.com/rounders/ember-world-flags#testing-paths" 
```

Let me know if that fixes the issue for you?

**Comment by artsyca** [comment]
Aha I see the path is now relative (`../ember-world-flags`) and I believe it should work. I can't test until Saturday when I'm back at the office but I think it ought to work.

I believe as well, the addon css will always get merged with vendor.css so you can move the styles from `vendor/styles/*` to `addon/styles/*` and they'll be loaded automatically without the need for the calls to `target.import` in index.js.

<img width="206" alt="image" src="https://user-images.githubusercontent.com/364015/217690525-13c7fd34-18fd-426f-a0b6-692846c305f7.png">

I don't recall seeing anything about using relative paths for css images in addons however and I wonder about it a little.

**Comment by rounders** [comment]
@artsyca thanks for the tip regarding moving the styles into addon/styles/ and not needing target.import, I'll give that a try tomorrow.

**Comment by rounders** [comment]
I've deployed version 1.8.0 which hopefully fixes your issue and incorporates your suggestion of putting the css files in addon/styles which I see is indeed the right way to do it according to the ember docs.

**Comment by nova-alex** [comment]
Works amazingly, very much appreciated.
I'm still not 100% sold on the idea that all addons need to use relative asset paths in order to work with `rootURL` .. I thought the build pipeline took care of that somehow?

At any rate, this work marvellously and I'm very grateful to all your work on this useful plugin.

**Comment by rounders** [comment]
@nova-alex great, glad it's working for you. Thanks for the help with this issue!
