### ISSUE TITLE
Flags don't seem to be rendering in the demo app

### ISSUE THREAD

**Issue by elwayman02** [rounders/ember-world-flags#9]
<img width="727" alt="ember-world-flags_demo" src="https://user-images.githubusercontent.com/1325482/31038821-b2300f5c-a52d-11e7-9ba9-c5ee83d5cfe5.png">

**Comment by rounders** [comment]
@elwayman02 I initially messed up when I first deployed the demo app but I fixed it a couple minutes afterwards. Can you have another look at http://rounders.github.io/ember-world-flags/ when you have a chance and let me know if it works for you now ?

**Comment by JorgeCoock** [comment]
still broken, the next errors appears on the console:
`Failed to find a valid digest in the 'integrity' attribute for resource 'http://rounders.github.io/ember-world-flags/assets/vendor-4fb355e583f1250380944a602976a832.css' with computed SHA-256 integrity 'n1fBVglA5VK3cR7qEVXDV7YKC+yzNFilgECZKE+HqUQ='. The resource has been blocked.`

**Comment by rounders** [comment]
@JorgeCoock thanks, I'll see if I can track that down. When i view the page with safari It seems to work fine and no console errors, but I was able to see the console error that you mentioned when using chrome.

**Comment by rounders** [comment]
ok this is fixed now on chrome. 

The gh-pages build produced by ember-cli-github-pages has a bug with public asset locations. So to fix that, I have to manually edit the vendor.css file and doing so changes the computed integrity value of the file. So in the demo app I just set the integrity value to "" for the vendor.css file in index.html
